### ISSUE TITLE
Question: Do I need a Database table for each Entity

### ISSUE THREAD

**Issue by lamp** [fredwu/datamappify#12]
To use the example in the README, 

If I have a `User` entity with a `UserAccount` model it seems according to my experience that I would also need a `users` table.

Is this meant to be the case, and if so how can I get around it?

**Comment by fredwu** [comment]
Hi @lamp, yes and no. Yes you do need _a_ table, but it doesn't necessarily have to be called `users`. It's whatever table your ORM model specifies, if any.

Entities have no knowledge of persistence (and DB tables), and that's by design. Your repositories should be responsible for "glueing" your entities with the DB tables via mapping.

**Comment by lamp** [comment]
Hi @fredwu, thanks for your answer.

If I could get your eye on what I've been doing wrong that would be great, here is a general gist of my code:

in app/models/retailer.rb

```
  class Retailer < ActiveRecord::Base
  end
```

in app/entities/organisation.rb

```
  class Organisation
    include Datamappify::Entity
    attr_accessor :retailer

    attribute :name, String
```

in app/repositories/organisation_repository.rb

```
 class OrganisationRepository
   include Datamappify::Repository

   for_entity Organisation

   default_provider :ActiveRecord
   map_attribute :name, "ActiveRecord::Retailer#name"
```

If I then run `OrganisationRepository.find(1)` I will get the error

```
   Mysql2::Error: Table 'mydb_development.organisations' doesn't exist: SHOW FULL FIELDS FROM `organisations`
```

I did trace this through the code and it seems that for_entity requires an AR model, unless I am doing something very stupid.

**Comment by fredwu** [comment]
Ah I see. Yes that is correct, by default there should always be an ORM model that has the same name as the entity. For now, you can get around it by having an `organisations` table (the corresponding ActiveRecord model will be created for you automatically).

**Comment by lamp** [comment]
Thanks for your response, you've been very helpful.
