### ISSUE TITLE
Load entity relations

### ISSUE THREAD

**Issue by mattbeedle** [fredwu/datamappify#15]
Hey,

When you load an entity it doesn't populate any related entities. Is this a bug or is it intended functionality?

``` ruby
class Deployment
  include Datamappify::Entity

  attribute :name

  references :user
end

class User
  include Datamappify::Entity

  attribute :email
end


DeploymentRepository.find(1) # => deployment

deployment.user_id # => 1
deployment.user # => nil
```

**Comment by fredwu** [comment]
That is by design (or lack thereof). Datamappify does not (currently) support entity relationships. The `references` DSL is merely a convenient method for assigning value to `user_id`:

``` ruby
attribute :user_id, Integer
attr_reader :user

def user=(entity)
  @user = entity
  self.user_id = entity.nil? ? nil : entity.id
end
```

**Comment by mattbeedle** [comment]
Ok, that's what I thought. Are entity relationships something that you would like to support in the future? They seem like a nice idea to me. Maybe I could find some time to implement that.

**Comment by fredwu** [comment]
I haven't figured out a way to implement it nicely - by design, a repository is responsible for retrieving an entity. A different entity would require a different repository to handle it - and the entity should not have any knowledge about its repository.

For now in our app we use service objects to wrap entities. :)

**Comment by benaskins** [comment]
Out of interest @fredwu - do your service objects talk to both entities and repositories? I'm trying to establish some conventions for a new app we're building, and my first service object looks a little like this:

``` ruby
class QuoteRequest

  attr_reader :quote

  def initialize(params={})
    @quote = Quote.new(params)
  end

  def calculate_price
    # Price calculation logic goes here
  end

  def process
    calculate_price
    save
  end


  private

  def save
    QuoteRepository.save(@quote)
  end
end
```

and using it in a controller like this:

``` ruby
def create
  quote_request = QuoteRequest.new(params[:quote])
  quote_request.process
  respond_with quote_request.quote
end
```

Hopefully I'm not taking too many liberties discussing this on issues, but I'm not sure of a better forum :8ball:

**Comment by fredwu** [comment]
@benaskins Yes in the service objects you'd access both entities and repositories. What you've done here looks good to me. :)

**Comment by benaskins** [comment]
Sweet, thanks mate!

**Comment by fredwu** [comment]
Please give the new [experimental association support](https://github.com/fredwu/datamappify#association) a try. ;)
