### ISSUE TITLE
Change behaviour of default_provider

### ISSUE THREAD

**Issue by benaskins** [fredwu/datamappify#17]
I've come across a scenario where default_provider is not behaving the way I'd expect it to. I have an entity like this, with some attributes I'd like to persist, and some that I'd prefer not to.

``` ruby
class Quote
  include Datamappify::Entity

  # Attributes I want to persist
  attribute :departs_on, Date
  attribute :returns_on, Date

  # Attributes I don't want to persist
  attribute :num_travellers, Integer
  attribute :policy_holder, PolicyHolder
end
```

With a repository like this:

``` ruby
class QuoteRepository
  include Datamappify::Repository

  for_entity Quote

  default_provider :ActiveRecord

  map_attribute :departs_on, :to => 'Quote#departs_on'
  map_attribute :returns_on, :to => 'Quote#returns_on'
end
```

When I persist the entity via the repository, it tries to persist num_travellers and policy_holder. After some digging I figured this was due to the default_provider.

If I remove the default_provider like so:

``` ruby
class QuoteRepository
  include Datamappify::Repository

  for_entity Quote

  group :provider => :ActiveRecord do
    map_attribute :departs_on, :to => 'Quote#departs_on'
    map_attribute :returns_on, :to => 'Quote#returns_on'
  end
end
```

I think persistence works as I'm expecting, with only the mapped attributes being persisted.

However the repository finder doesn't work. If I do something like this:

``` ruby
QuoteRepository.find(1)
```

I get the following exception:

```
TypeError: wrong argument type nil (expected String)
    from /Users/benaskins/.rvm/gems/ruby-2.0.0-p195/bundler/gems/datamappify-b4646c3a4b88/lib/datamappify/data/mapper.rb:33:in `const_get'
    from /Users/benaskins/.rvm/gems/ruby-2.0.0-p195/bundler/gems/datamappify-b4646c3a4b88/lib/datamappify/data/mapper.rb:33:in `default_provider'
    from /Users/benaskins/.rvm/gems/ruby-2.0.0-p195/bundler/gems/datamappify-b4646c3a4b88/lib/datamappify/repository/query_method/method.rb:69:in `dispatch_criteria_to_default_source'
    from /Users/benaskins/.rvm/gems/ruby-2.0.0-p195/bundler/gems/datamappify-b4646c3a4b88/lib/datamappify/repository/query_method/find.rb:10:in `perform'
    from /Users/benaskins/.rvm/gems/ruby-2.0.0-p195/bundler/gems/datamappify-b4646c3a4b88/lib/datamappify/repository/query_methods.rb:28:in `find'
```

I'd like to either go down the path of removing `find's` dependency on default_provider, or the way persistence works to only map the attributes that contain a mapping in the repository. I can see the convenience of auto-mapping unmapped attributes in the repo, but it feels like I'm then tightly coupling my entities to the persistence layer.

Before I head down this path, what are your thoughts? Would you be open to datamappify being changed in this way? I don't want to invest the time in making these changes if they're unlikely to be rolled in.

**Comment by benaskins** [comment]
I could use attr_accessor on entities for attributes that I don't want to be persisted, but then I'm introducing awareness of persistence into my domain models.

**Comment by fredwu** [comment]
Ah, yeah I think making `default_provider` optional makes sense. :)

**Comment by benaskins** [comment]
I've taken a slightly different tack and have introduced an automap
accessor to Data::Mapper. When set to false this changes the behavior of
Data::Mapper#attributes to include only the custom_attributes (excluding
default_attributes). I'll send a patch through for your perusal once I've
got specs in place.

**Comment by fredwu** [comment]
Sweet, looking forward to that! :+1:

**Comment by benaskins** [comment]
I'm going to close this and pull request #18. Unfortunately the automap feature has broken the support you added for associations.

I think I'm going to have to bite the bullet and roll my own dumbed down repository layer that can just map Virtus objects to ActiveRecord::Base objects - I'm pretty sure that's all I need out of a repository. I appreciate all of the magic you've got going on here, but it's starting to get in my way.

Great work so far @fredwu - I'm looking forward to seeing where you head with this!

**Comment by fredwu** [comment]
Thanks @benaskins !

The association support is experimental and it has issues of its own that I am currently trying to solve - I would still love to incorporate your changes once I have the association stuff to a more stable state.

**Comment by benaskins** [comment]
No worries @fredwu - if you think you can use what I wrote, please do! For now I've implemented a simple entity/repository pair over here https://github.com/benaskins/entity_mapper

It's heavily inspired by what you've done, but significantly more lo-fi.
