### ISSUE TITLE
Why isn't this gem 1.0.0?

### ISSUE THREAD

**Issue by krainboltgreene** [fredwu/datamappify#2]
I've noticed you're using semantic versioning, but the gem isn't 1.0.0? You have people who depend on this gem, have a stable public API,  and it does at least the basics of what it set out to do.

Don't worry about needing to change the public API in the future, semantic versioning takes care of this by requiring a major version bump. Let people use the intelligent optimistic versioning for your gem in a meaningful way.

**Comment by fredwu** [comment]
I prefer to release 1.0.0 when I consider the library to be stable. At the moment we are still in early stages developing against using Datamappify. When we are happy with Datamappify's API then we'll release 1.0.0. :)

**Comment by krainboltgreene** [comment]
5,159 times someone decided your gem was stable enough to use.

That's the qualifier for a semantic 1.0.0 version as described by semver.org.
Being 0.x when you don't need to be strips away the usefulness and
intelligence of optimistic versioning that gemcutter gives developers and
helps propagates the idea that ruby gems are underdeveloped.

Don't be scared of 1.0.0. **It doesn't mean you're done coding.**

**Comment by fredwu** [comment]
I totally understand where you are coming from. A 1.0.0 will be released in the next week or two. :)
