### ISSUE TITLE
change implicit table

### ISSUE THREAD

**Issue by semmons99** [fredwu/datamappify#29]
Hi @fredwu 

I'm trying to break apart a giant table into separate entities. In the code below I'd like it to still reference the "teams" table, even though the for_entity is TeamPreferences. I thought telling it the id was on the teams table would work, but no such luck. Any suggestions?

``` ruby
class TeamPreferencesRepository
  include Datamappify::Repository

  for_entity TeamPreferences

  map_attribute :id, :to => "Team#id"
  map_attribute :refreshments_show_tab, :to => "Team#show_refreshments"
  map_attribute :refreshments_enable_for, :to => "Team#refreshments_filter"
end
```

I'm doing this to break apart a giant teams table in the api, before breaking it apart in the database.

**Comment by fredwu** [comment]
Hi, unfortunately Datamappify does not support custom primary key yet. That means that you have to have a `TeamPreferences' ActiveRecord model (which Datamappify builds for you on the fly if it's not there).

**Comment by semmons99** [comment]
@fredwu so, I could manually build the Sequel model (I ditched ActiveRecord) and tell it to use the "team" table instead of the team_preferences table it would default to. Then, the mapping should switch to TeamPreferences#id, correct?

**Comment by fredwu** [comment]
Yep, that should work. :)
