### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by tobinharris** [fredwu/datamappify#31]
This looks like something I'd use. Is it maintained and is anyone using it in production?
T

**Comment by fredwu** [comment]
We were using it for a couple of months, unfortunately we've decided to pull it out so it's not being maintained anymore, sorry.

**Comment by tobinharris** [comment]
Thanks! 

Would you mind sharing what you ended up using?

I'm guessing Sequel from your blog?

I'm looking for a way of achieving lighting fast unit testing, and also somehow teasing out the coupling of persistence in my app. 

T

**Comment by fredwu** [comment]
We ended up using the good'ol ActiveRecord for maximum compatibility with gems.

**Comment by tobinharris** [comment]
Cheers
