### ISSUE TITLE
Devise

### ISSUE THREAD

**Issue by mattbeedle** [fredwu/datamappify#5]
How would I use this with devise? I tried creating a SignupEntity, a SignupRepository and a devise User, but when I try to save the signup with:

``` ruby
SignupRepository.save(signup)
```

I get this error:

``` ruby
ActiveRecord::UnknownAttributeError: unknown attribute: password
```

**Comment by fredwu** [comment]
The way we use Devise, is to have a `UserAccount` ActiveRecord model. So the authentication is handled by Devise via this model. And things such as username/email can then be mapped onto a `User` entity via repository. :)

**Comment by fredwu** [comment]
Closing this for now. :)
