### ISSUE TITLE
An alternate map_attribute API

### ISSUE THREAD

**Issue by stevenharman** [fredwu/datamappify#8]
Upon seeing it, and even after understanding what it does, I find the `map_attribute` API surprising. Specifically the second argument.

``` ruby
map_attribute :account_username,  'ActiveRecord::UserAccount#username'
```

That string looks like a namespace. And what if my `UserAccount` object is namespaced under an `Admin` module? Does it become

``` ruby
map_attribute :account_username,  'ActiveRecord::Admin::UserAccount#username'
```

What about the following API:

``` ruby
map_attribute :account_username,  to: 'UserAccount#username', with: 'ActiveRecord'
```

The `:with` could be optional, defaulting the the `default_provider` specified elsewhere. This also reduces some unnecessary duplication. Also, the `:to` argument is now more intention revealing, and a more direct mapping to a Ruby object and method name.

In the case of a namespaced object you could say `to: 'Admin::UserAccount#username'`. And in the case of an ambiguous constant, you could fully qualify via `to: '::UserAccount#username'`.

Thoughts?

**Comment by locochris** [comment]
@stevenharman what about:

``` ruby
using 'ActiveRecord' do
  map_attribute :account_username,  to: 'UserAccount#username'
end
```

Or using some nice convention over configuration defaults:

``` ruby
using 'ActiveRecord' do
  map_attribute :user_account__username
end
```

**Comment by stevenharman** [comment]
I suppose wrapping the config in a block where you specify a local default provider is kind of nice for when you want to map many things at once. Though the more verbose `:with` option is also nice for a single, or just a few, mappings.

I don't really like the double underscore to denote the method name.

**Comment by fredwu** [comment]
I like the block level style, it is explicit, readable and doesn't require more keystrokes. :)

**Comment by locochris** [comment]
So best of all worlds?
ie. allow using a block, or the more verbose single option.  :)

Agreed, that double underscore doesn't look pretty...
How bout drying it up another way:

``` ruby
using 'ActiveRecord' do
  mapping 'UserAccount', :prefix => :account do
    map_attribute :username
  end
end
```

Or what about:

``` ruby
mapping 'UserAccount', :prefix => :account, :using => 'ActiveRecord' do
  map_attribute :username
end
```

**Comment by stevenharman** [comment]
@fredwu, Number of keystrokes seems an odd thing to optimize for, over intent and clarity. :wink:

@locochris, Remember:

> DRY isn’t about the repetition of structure, it’s about the duplication of knowledge.

At any rate, of the block syntaxes, I prefer the last one, I think. Even then, the `:using` option _could_ default to the specified `default_provider`.

:heart: for the communication and feedback, all.

**Comment by locochris** [comment]
@stevenharman if you go with the `default_provider` idea it'd probably make more sense to
compliment that by using the word `:provider` instead of `:using`

**Comment by fredwu** [comment]
How about this?

``` ruby
with_provider :ActiveRecord do
  map_attribute :account_username, to: 'UserAccount#username'
end

# and

map_attribute :account_username, to: 'UserAccount#username', :with_provider: :ActiveRecord
```

**Comment by stevenharman** [comment]
@fredwu That seems reasonable.

**Comment by fredwu** [comment]
FYI I'm going to let the `:via` option act the same way, in that case I think I will make it:

``` ruby
group :provider: :ActiveRecord, via: :user_id do
  map_attribute :account_username, to: 'UserAccount#username'
end

# and

map_attribute :account_username, to: 'UserAccount#username', :provider: :ActiveRecord, via: :user_id
```
